"""
Automated Ecological Alert System for Blue.AI.
Monitors funded mangrove zones and sends alerts when health degrades.
Designed to be called by a scheduled job (cron / Render scheduled service).
"""
import logging
import datetime
import os
from typing import Optional
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

ALERT_THRESHOLD_PCT = 0.10  # 10% NDVI decline triggers alert
ALERT_COOLDOWN_DAYS = 7     # Minimum days between alerts for same zone

def send_email_alert(to_email: str, subject: str, html_body: str) -> bool:
    """
    Send alert email via SMTP. Reads credentials from environment.
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD env vars.
    Falls back to logging if email not configured.
    """
    smtp_host = os.environ.get('SMTP_HOST')
    smtp_user = os.environ.get('SMTP_USER')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    smtp_port = int(os.environ.get('SMTP_PORT', '587'))
    from_email = os.environ.get('SMTP_FROM', 'alerts@blueai.in')
    
    if not smtp_host or not smtp_user:
        logger.warning(f"Email not configured. Alert would have gone to {to_email}: {subject}")
        return False
    
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"Blue.AI Alerts <{from_email}>"
        msg['To'] = to_email
        msg.attach(MIMEText(html_body, 'html'))
        
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(from_email, to_email, msg.as_string())
        
        logger.info(f"Alert sent to {to_email}: {subject}")
        return True
    except Exception as e:
        logger.error(f"Email send failed: {e}")
        return False

def build_alert_email(alert: dict, recipient_type: str) -> str:
    """Build HTML email body for an ecological alert."""
    status_color = '#dc2626' if alert['alert_level'] == 'critical' else '#ca8a04'
    status_text = 'CRITICAL DECLINE' if alert['alert_level'] == 'critical' else 'DECLINE DETECTED'
    
    role_msg = {
        'ngo': f"The mangrove zone you manage ({alert['area']}) is showing signs of stress.",
        'corporate': f"A mangrove zone you fund ({alert['area']}, managed by {alert.get('ngo_name','an NGO')}) is showing signs of stress.",
    }.get(recipient_type, f"Alert for zone {alert['area']}.")
    
    return f"""
    <div style="font-family:Inter,Arial,sans-serif;max-width:600px;margin:auto;background:#f0fafa;padding:20px;">
      <div style="background:#003e3f;padding:20px;border-radius:12px 12px 0 0;text-align:center;">
        <h1 style="color:#fff;margin:0;font-size:24px;">&#127807; Blue.AI</h1>
        <p style="color:#a3f0f0;margin:5px 0 0;">Ecological Monitoring Alert</p>
      </div>
      <div style="background:#fff;padding:30px;border-radius:0 0 12px 12px;border-top:4px solid {status_color};">
        <h2 style="color:{status_color};margin-top:0;">{status_text}</h2>
        <p style="color:#374151;">{role_msg}</p>
        <div style="background:#fef2f2;border-left:4px solid {status_color};padding:16px;border-radius:8px;margin:20px 0;">
          <strong>Zone:</strong> {alert['area']}<br>
          <strong>NDVI Change:</strong> {alert['change_pct']}% over 90 days<br>
          <strong>Current NDVI:</strong> {alert['current_ndvi']}<br>
          <strong>Baseline NDVI:</strong> {alert['baseline_ndvi']}<br>
          <strong>Detected:</strong> {alert['detected_at']}
        </div>
        <h3 style="color:#374151;">Possible Causes</h3>
        <ul style="color:#6b7280;">
          <li>Saltwater intrusion or flooding event</li>
          <li>Human activity or encroachment</li>
          <li>Disease or pest infestation</li>
          <li>Pollution from upstream sources</li>
          <li>Storm or cyclone damage</li>
        </ul>
        <h3 style="color:#374151;">Recommended Actions</h3>
        <ul style="color:#6b7280;">
          <li>Schedule an immediate field visit to assess on-the-ground conditions</li>
          <li>Document any visible damage with photographs and GPS coordinates</li>
          <li>Report to local forest department if human activity is suspected</li>
          <li>Update your project log on Blue.AI with findings</li>
        </ul>
        <a href="https://blueai.in/ngo/insights" style="display:inline-block;background:#003e3f;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;margin-top:10px;">View Full Satellite Report &rarr;</a>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:20px 0;">
        <p style="color:#9ca3af;font-size:12px;">
          This alert was generated by Blue.AI's automated ecological monitoring system.<br>
          Data source: Copernicus Sentinel-2 SR via Google Earth Engine.<br>
          To adjust alert thresholds, visit your profile settings.
        </p>
      </div>
    </div>
    """

def check_and_send_alerts(db, force: bool = False) -> dict:
    """
    Main function: check all NGO zones, compare NDVI, send alerts if threshold exceeded.
    Meant to be called by a scheduled job (daily/weekly).
    
    Args:
        db: Firestore client
        force: If True, ignore cooldown period (for testing)
    
    Returns: Summary dict of alerts sent/skipped
    """
    if not db:
        return {'error': 'Database not available', 'alerts_sent': 0}
    
    from .health_tracker import assess_patch_health
    
    summary = {'checked': 0, 'alerts_sent': 0, 'skipped_cooldown': 0, 'errors': 0}
    
    try:
        # Get all NGOs with their areas
        ngos = list(db.collection('users').where('type', '==', 'ngo').stream())
        
        for ngo_doc in ngos:
            ngo_data = ngo_doc.to_dict()
            area = ngo_data.get('area')
            ngo_email = ngo_data.get('email')
            
            if not area or not ngo_email:
                continue
            
            summary['checked'] += 1
            
            # Check cooldown
            if not force:
                alert_log = db.collection('alert_log').where(
                    'ngo_id', '==', ngo_doc.id
                ).where('status', '==', 'sent').order_by('sent_at', direction='DESCENDING').limit(1).stream()
                
                last_alert_docs = list(alert_log)
                if last_alert_docs:
                    last_sent = last_alert_docs[0].to_dict().get('sent_at', '')
                    if last_sent:
                        try:
                            last_dt = datetime.datetime.fromisoformat(last_sent)
                            days_since = (datetime.datetime.utcnow() - last_dt).days
                            if days_since < ALERT_COOLDOWN_DAYS:
                                summary['skipped_cooldown'] += 1
                                continue
                        except:
                            pass
            
            # Assess health
            try:
                health = assess_patch_health(area)
                
                if health.get('status') not in ('declining',) and not health.get('error'):
                    continue
                
                if health.get('error'):
                    summary['errors'] += 1
                    continue
                
                change_pct = abs(health.get('change_pct', 0))
                alert_level = 'critical' if change_pct > 20 else 'warning'
                
                alert = {
                    'ngo_id': ngo_doc.id,
                    'ngo_name': ngo_data.get('name'),
                    'area': area,
                    'alert_level': alert_level,
                    'change_pct': round(-change_pct, 1),
                    'current_ndvi': health.get('current_ndvi', 0),
                    'baseline_ndvi': health.get('baseline_ndvi', 0),
                    'detected_at': datetime.datetime.utcnow().strftime('%d %B %Y, %H:%M UTC'),
                    'status': 'sent',
                    'sent_at': datetime.datetime.utcnow().isoformat(),
                }
                
                # Alert NGO
                ngo_html = build_alert_email(alert, 'ngo')
                subject = f"Blue.AI Alert: Mangrove health declining in {area}"
                ngo_sent = send_email_alert(ngo_email, subject, ngo_html)
                
                # Alert all corporates who donated to this NGO
                corp_sent_count = 0
                donations = list(db.collection('donations').where('ngo_id', '==', ngo_doc.id).stream())
                donor_ids = set(d.to_dict().get('donor_id') for d in donations if d.to_dict().get('donor_id'))
                
                for donor_id in donor_ids:
                    corp_doc = db.collection('users').document(donor_id).get()
                    if corp_doc.exists:
                        corp_data = corp_doc.to_dict()
                        corp_email = corp_data.get('email')
                        if corp_email:
                            corp_html = build_alert_email({**alert, 'ngo_name': ngo_data.get('name')}, 'corporate')
                            send_email_alert(corp_email, subject, corp_html)
                            corp_sent_count += 1
                
                # Log alert
                db.collection('alert_log').add(alert)
                
                if ngo_sent or corp_sent_count > 0:
                    summary['alerts_sent'] += 1
                    
            except Exception as e:
                logger.error(f"Alert check failed for NGO {ngo_doc.id}: {e}")
                summary['errors'] += 1
    
    except Exception as e:
        logger.error(f"Alert batch failed: {e}")
        summary['error'] = str(e)
    
    logger.info(f"Alert sweep complete: {summary}")
    return summary
